runtime: python27
threadsafe: true
api_version: 1
basic_scaling:
  max_instances: 2

handlers:
# The endpoints handler must be mapped to /_ah/api.
- url: /_ah/api/.*
  script: register.application

libraries:
- name: pycrypto
  version: 2.6
- name: ssl
  version: 2.7.11

# [START env_vars]
env_variables:
  # The following values are to be replaced by information from the output of
  # 'gcloud endpoints services deploy swagger.json' command.
  ENDPOINTS_SERVICE_NAME:  bicycle-store-195204.appspot.com
  ENDPOINTS_SERVICE_VERSION: 2018-01-14r1
# [END env_vars]
